"""Add sessions table

Revision ID: 0742d8e39597
Revises: 155d0e9ee80f
Create Date: 2026-08-09 16:11:35.441619

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0742d8e39597'
down_revision: str | Sequence[str] | None = '155d0e9ee80f'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('family_id', sa.Uuid(), nullable=False),
    sa.Column('hashed_refresh_token', sa.String(), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_sessions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sessions'))
    )
    op.create_index(op.f('ix_sessions_family_id'), 'sessions', ['family_id'], unique=False)
    op.create_index(op.f('ix_sessions_hashed_refresh_token'), 'sessions', ['hashed_refresh_token'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sessions_hashed_refresh_token'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_family_id'), table_name='sessions')
    op.drop_table('sessions')
    # ### end Alembic commands ###
